-- ── 024_biography.sql ────────────────────────────────────────────────────────
-- Add 'biography' post type, Biography category, and 15 seed articles

-- ── Extend type constraint ────────────────────────────────────────────────────
ALTER TABLE knowledge_posts DROP CONSTRAINT IF EXISTS knowledge_posts_type_check;
ALTER TABLE knowledge_posts
  ADD CONSTRAINT knowledge_posts_type_check
  CHECK (type IN ('article', 'quote', 'tip', 'blog', 'biography'));

-- ── Biography category ────────────────────────────────────────────────────────
INSERT INTO knowledge_categories (name_en, name_lo, slug, icon, color, sort_order)
VALUES ('Biography', 'ຊີວະປະຫວັດ', 'biography', '👤', 'indigo', 7)
ON CONFLICT (slug) DO NOTHING;

-- ── Biography seed articles ───────────────────────────────────────────────────
DO $$
DECLARE
  bio_cat_id UUID;
BEGIN
  SELECT id INTO bio_cat_id FROM knowledge_categories WHERE slug = 'biography';

  -- 1. Elon Musk
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Elon Musk: The Man Who Bets Everything on the Future',
    'ອີລອນ ມັສ: ຜູ້ທີ່ເດີມພັນທຸກຢ່າງໃສ່ອະນາຄົດ',
    'From a bullied child in South Africa to the world''s richest man — Elon Musk''s story is one of relentless ambition, near-bankruptcy, and an obsession with making humanity multi-planetary.',
    E'## Early Life\n\nElon Reeve Musk was born on June 28, 1971, in Pretoria, South Africa. A quiet, bookish child who read encyclopedias for fun, he was badly bullied and found refuge in computers and books. At 12, he sold his first computer game, Blastar, for $500.\n\nAt 17 he moved to Canada to avoid mandatory military service, working odd jobs before enrolling at Queen''s University and later transferring to the University of Pennsylvania, where he earned degrees in economics and physics.\n\n## The Road to Success\n\nIn 1995, Musk moved to California for a Stanford PhD — and dropped out after two days to start Zip2, a software company he sold for $307 million in 1999. He then founded X.com (later PayPal), which sold to eBay for $1.5 billion.\n\nRather than retire, he used every dollar to start two companies the world called crazy:\n- **Tesla** (2004) — to accelerate the world''s transition to sustainable energy\n- **SpaceX** (2002) — to make humanity a multi-planetary species\n\nIn 2008, both companies were days from bankruptcy. Musk split his last $30 million between them and didn''t know if either would survive. SpaceX''s fourth rocket launch succeeded on the final attempt. Tesla secured emergency funding hours before collapse.\n\n## Key Principles\n\n**First Principles Thinking**: Instead of reasoning by analogy (\"batteries are expensive because they''ve always been expensive\"), Musk breaks problems to their physical fundamentals and rebuilds from scratch.\n\n**Extreme Ownership**: If something fails, it''s not someone else''s fault — it''s yours to fix.\n\n**Speed Beats Perfection**: Ship fast, fail fast, iterate fast. Rockets and cars can be redesigned; lost time cannot.\n\n**The Mission Is Everything**: Musk repeatedly said he didn''t start Tesla or SpaceX to get rich — he started them because he believed civilization needed them.\n\n## Legacy\n\nToday, SpaceX reuses orbital rockets (once thought impossible), Tesla is the most valuable car company on Earth, and Musk is reshaping AI through xAI. Love him or loathe him, he has changed the economics of space, energy, and transportation forever.\n\n**Greatest lesson**: The most important question you can ask is: "What would be good for humanity?" Build that.',
    'Bitdoin Team',
    ARRAY['elon-musk', 'tesla', 'spacex', 'entrepreneurship', 'innovation', 'first-principles'],
    true, true, 0
  );

  -- 2. Steve Jobs
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Steve Jobs: The Artist Who Built the Digital Age',
    'ສະຕີຟ ຈ໊ອບ: ສິລະປິນທີ່ສ້າງຍຸກດິຈິຕ້ອລ',
    'Adopted, college dropout, fired from his own company — and yet Steve Jobs revolutionized six industries. His story is a masterclass in vision, simplicity, and the courage to think differently.',
    E'## Early Life\n\nSteve Paul Jobs was born February 24, 1955, in San Francisco, and adopted as an infant by Paul and Clara Jobs. Growing up in Silicon Valley in the 1960s, he was surrounded by engineers and spent his teens in their garages, learning how things worked.\n\nHe enrolled at Reed College in Oregon — and dropped out after one semester, feeling guilty about the tuition cost burdening his working-class parents. He slept on floors, returned Coke bottles for food money, and crashed calligraphy classes just because they interested him.\n\n## Building Apple\n\nIn 1976, at 21, Jobs co-founded Apple Computer with Steve Wozniak in his parents'' garage. The Apple II (1977) was a breakthrough. The Macintosh (1984) launched with a now-legendary Super Bowl commercial and introduced the world to the graphical interface.\n\nBut in 1985, Jobs was forced out of Apple by his own board. Instead of quitting tech, he started **NeXT** and bought a small animation studio that became **Pixar**. Pixar''s Toy Story (1995) changed cinema. When Apple bought NeXT in 1997, Jobs returned — and began one of the greatest corporate comebacks in history.\n\n## The Second Act\n\nFrom 1997 to 2011, Jobs introduced:\n- The iMac (1998) — design as product\n- iTunes + iPod (2001) — reinvented music\n- iPhone (2007) — reinvented communication\n- iPad (2010) — reinvented computing\n- App Store — created a trillion-dollar ecosystem\n\n## Key Principles\n\n**Simplicity is the ultimate sophistication**: Real creativity is saying no to 1,000 things.\n\n**Design is not just looks — it''s how it works**: Every product decision is a user experience decision.\n\n**Hire people smarter than you**: "It doesn''t make sense to hire smart people and then tell them what to do."\n\n**Connecting the dots**: You can''t connect the dots looking forward. Only looking backwards does the path become clear.\n\n## Legacy\n\nSteve Jobs died October 5, 2011, of pancreatic cancer at 56. He left behind the most valuable company in history, a standard for design that every tech product is still judged against, and the proof that technology and the humanities, married together, produce something magical.\n\n**Greatest lesson**: Stay hungry. Stay foolish.',
    'Bitdoin Team',
    ARRAY['steve-jobs', 'apple', 'innovation', 'design', 'leadership', 'creativity'],
    true, true, 0
  );

  -- 3. Bill Gates
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Bill Gates: The Programmer Who Changed Civilization',
    'ບິນ ເກດ: ໂປຣແກຣມເມີຜູ້ປ່ຽນອາລະຍະທຳ',
    'Bill Gates dropped out of Harvard to chase a vision: a computer on every desk, in every home. That bet made him the world''s richest man for decades — and he''s now betting everything to save lives.',
    E'## Early Life\n\nWilliam Henry Gates III was born October 28, 1955, in Seattle, Washington, into a family of lawyers and civic leaders. By 13 he was already obsessed with computers, spending nights coding on the school''s terminal. He formed his first company, Traf-O-Data, at 17 with Paul Allen.\n\nHe enrolled at Harvard in 1973 — and in 1975, dropped out to start Microsoft. The decision horrified his parents. It transformed the world.\n\n## Building Microsoft\n\nMicrosoft''s decisive moment came in 1980: IBM needed an operating system for its new personal computer. Gates didn''t have one — so he bought QDOS for $50,000 and licensed it to IBM as MS-DOS. The genius wasn''t the code. It was keeping the licensing rights.\n\nAs IBM clones flooded the market, every one needed MS-DOS. Then Windows. Then Office. Gates understood software''s nature: copy it once, sell it a billion times.\n\nBy 1995, Windows 95 launched like a rock concert. Microsoft became the most valuable company on Earth, and Gates the richest person on Earth — a position he held for much of the next two decades.\n\n## Key Principles\n\n**Think systems, not products**: Gates always saw software as infrastructure — the invisible layer that makes everything else possible.\n\n**Read voraciously**: Gates reads 50 books a year and takes a famous "Think Week" twice yearly — alone in a cabin, reading and writing.\n\n**Optimism backed by data**: The world is getting better. Gates uses data and charts to show trends that our instincts miss.\n\n**Giving back is the job**: In 2000, Gates left Microsoft to focus on the Bill & Melinda Gates Foundation, committing $50 billion to global health, education, and poverty.\n\n## Legacy\n\nThe Gates Foundation has contributed to eradicating polio, developing vaccines, and reforming education. Gates has pledged over 99% of his wealth to philanthropy. From building the software stack civilization runs on, to trying to defeat the diseases that kill the poorest — Bill Gates is one of the most consequential humans of the modern era.\n\n**Greatest lesson**: "It''s fine to celebrate success but it is more important to heed the lessons of failure."',
    'Bitdoin Team',
    ARRAY['bill-gates', 'microsoft', 'software', 'philanthropy', 'technology'],
    true, true, 0
  );

  -- 4. Jeff Bezos
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Jeff Bezos: From Garage to the Stars',
    'ເຈັ໋ຟ ເບໂຊ: ຈາກໂຮງຈອດລົດສູ່ດວງດາວ',
    'Jeff Bezos left a high-paying Wall Street job to sell books from a garage. He called it a risky bet. It became the engine of modern commerce — and launched him into space.',
    E'## Early Life\n\nJeffrey Preston Jorgensen was born January 12, 1964, in Albuquerque, New Mexico. When his mother remarried a Cuban immigrant named Miguel Bezos, Jeff took his stepfather''s name. He grew up tinkering — converting his room into a lab, repairing electronics, and reading voraciously.\n\nHe graduated from Princeton with degrees in computer science and electrical engineering, then joined the finance world, rising to senior VP at hedge fund D.E. Shaw.\n\n## The Leap\n\nIn 1994, Bezos read a statistic that the internet was growing 2,300% per year. He made a list of potential internet businesses and landed on books: millions of titles, a clear product, easy to ship. He drove cross-country to Seattle, writing the business plan in the car while his wife drove.\n\nAmazon launched from a garage in 1995. Bezos told early investors there was a 70% chance they''d lose everything. He called his approach "a regret minimization framework" — imagining himself at 80, which decision would he regret more?\n\n## Building an Empire\n\nAmazon expanded from books to everything. Key inflection points:\n- **Amazon Prime** (2005) — loyalty flywheel\n- **AWS / Amazon Web Services** (2006) — cloud computing for the world; now the most profitable part of Amazon\n- **Kindle** (2007) — digitized reading\n- **Alexa & Echo** (2014) — voice as interface\n- **Acquisitions**: Whole Foods, Twitch, MGM studios\n\n## Key Principles\n\n**Think long-term**: Amazon operated at a loss for years, reinvesting everything. Wall Street hated it. The compound returns rewarded patient investors.\n\n**Work backwards from the customer**: Start with the press release, then build the product. The customer''s need drives every decision.\n\n**Two-pizza rule**: If a team can''t be fed by two pizzas, it''s too big.\n\n**Day 1 mentality**: Day 2 is stasis, followed by irrelevance, followed by death. Always behave like it''s the first day of your company.\n\n## Legacy\n\nBezos stepped down as Amazon CEO in 2021 to focus on **Blue Origin**, his space company with the mission of moving heavy industry off Earth. He''s also the owner of The Washington Post. He has pledged $10 billion to fight climate change via the Bezos Earth Fund.\n\n**Greatest lesson**: "If you''re not stubborn, you''ll give up on experiments too soon. If you''re not flexible, you''ll pound your head against the wall."',
    'Bitdoin Team',
    ARRAY['jeff-bezos', 'amazon', 'e-commerce', 'aws', 'leadership', 'innovation'],
    true, false, 0
  );

  -- 5. Warren Buffett
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Warren Buffett: The Oracle of Omaha''s Lifetime of Patience',
    'ວໍເຣັນ ບັຟເຟັດ: ຊີວິດຂອງຄວາມອົດທົນ',
    'Warren Buffett started investing at 11, filed his first tax return at 13, and built Berkshire Hathaway into a $900 billion empire — not by chasing trends, but by waiting for great companies at fair prices.',
    E'## Early Life\n\nWarren Edward Buffett was born August 30, 1930, in Omaha, Nebraska. From childhood, he showed an extraordinary affinity for numbers and business. At 11, he bought his first stock (Cities Service Preferred). At 13, he delivered newspapers and earned enough to file his first tax return — deducting his bicycle as a business expense.\n\nHe sold chewing gum door to door, delivered pinball machines, and filed his first tax return at 13. When he graduated high school, he had saved $6,000 (about $70,000 today).\n\n## The Education\n\nBuffett applied to Harvard Business School and was rejected. He enrolled at Columbia University after reading Benjamin Graham''s book "The Intelligent Investor" — a book he called "by far the best book ever written on investing." Graham''s philosophy of buying dollar bills for fifty cents became Buffett''s foundation.\n\n## Building Berkshire Hathaway\n\nBuffett ran his investment partnership through the 1950s–60s, outperforming the market dramatically. In 1965, he took control of Berkshire Hathaway — then a failing textile company — and transformed it into a holding company for exceptional businesses.\n\nKey investments that define his philosophy:\n- **Coca-Cola** (1988) — bought when others feared the Pepsi Challenge\n- **Apple** (2016) — his largest holding; called it "a better business than any we own"\n- **GEICO, American Express, Bank of America** — trusted brands at reasonable prices\n\n## Key Principles\n\n**Compound interest is the 8th wonder of the world**: Buffett started early and never stopped. 99% of his wealth was earned after his 50th birthday.\n\n**Invest in businesses, not stocks**: "It''s far better to buy a wonderful company at a fair price than a fair company at a wonderful price."\n\n**Circle of competence**: Only invest in what you understand. Buffett famously avoided tech stocks for decades.\n\n**Margin of safety**: Always buy at a significant discount to intrinsic value — it protects you when you''re wrong.\n\n**The Inner Scorecard**: Ask yourself: "Would I be comfortable if the person I respect most could see exactly what I''m doing and why?"\n\n## Legacy\n\nAt over 90, Buffett still reads 500 pages a day, still works out of the same Omaha office, and has pledged 99%+ of his wealth to the Gates Foundation and family charities. He and Charlie Munger built a culture of integrity at Berkshire that endures.\n\n**Greatest lesson**: "The most important investment you can make is in yourself."',
    'Bitdoin Team',
    ARRAY['warren-buffett', 'investing', 'berkshire-hathaway', 'value-investing', 'patience'],
    true, false, 0
  );

  -- 6. Mark Zuckerberg
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Mark Zuckerberg: Connecting the World, One Billion Users at a Time',
    'ມາກ ຊາກເກີເບີກ: ເຊື່ອມຕໍ່ໂລກ ທີລະຄົນ',
    'Mark Zuckerberg launched Facebook from his Harvard dorm room at 19. What started as a campus social network became the dominant platform for over 3 billion people — reshaping politics, business, and human connection.',
    E'## Early Life\n\nMark Elliot Zuckerberg was born May 14, 1984, in White Plains, New York. His father taught him Atari BASIC as a child, and by middle school he had built a messaging program called "ZuckNet" that his father used in his dental practice. At Phillips Exeter Academy, he built a music player (Synapse) that Microsoft and AOL tried to acquire for over $1 million — he turned them down.\n\n## The Dorm Room That Changed the World\n\nAt Harvard in 2003, Zuckerberg built Facemash — a "hot or not" site that crashed Harvard''s servers. It was offensive and he nearly got expelled. But it showed his instinct: people love comparing and connecting.\n\nIn February 2004, he launched "TheFacebook" for Harvard students. Within a month, half the campus had signed up. He dropped out of Harvard and moved to Palo Alto.\n\n## Building Meta\n\nFacebook''s growth was relentless:\n- **2006**: Opened to anyone with an email; News Feed launched\n- **2008**: Surpassed MySpace globally\n- **2012**: IPO raised $16 billion; acquired Instagram for $1 billion (now worth $100B+)\n- **2014**: Acquired WhatsApp for $19 billion\n- **2021**: Renamed to Meta; bet on the metaverse\n\n## Key Principles\n\n**Move fast and break things**: Facebook''s early motto. Now evolved to "Move fast with stable infrastructure."\n\n**Focus on what connects people**: Every product decision filters through: does this help people connect?\n\n**Long-term thinking**: Zuckerberg controls Meta through super-voting shares, insulating the company from short-term Wall Street pressure. He invests heavily in infrastructure others can''t see yet.\n\n**Learn from failure**: Instagram and WhatsApp looked expensive. Both proved to be Zuckerberg''s most important decisions.\n\n## Legacy\n\nFacebook/Meta has been criticized for privacy violations, spreading misinformation, and market dominance. Zuckerberg has navigated congressional hearings, $5 billion FTC fines, and public backlash — while continuing to build. The metaverse bet is still unproven, but his track record suggests underestimating him is risky.\n\n**Greatest lesson**: "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks."',
    'Bitdoin Team',
    ARRAY['mark-zuckerberg', 'facebook', 'meta', 'social-media', 'technology', 'entrepreneurship'],
    true, false, 0
  );

  -- 7. Jack Ma
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Jack Ma: The Teacher Who Defied Every Rejection',
    'ແຈັກ ມາ: ຄູສອນທີ່ສູ້ຄວາມລົ້ມເຫລວທຸກຢ່າງ',
    'Jack Ma failed his college entrance exam twice, was rejected by Harvard 10 times, and was turned down by KFC. He then built Alibaba into one of the world''s largest companies — proving persistence beats privilege every time.',
    E'## Early Life\n\nJack Ma (Ma Yun) was born September 10, 1964, in Hangzhou, China — a country then emerging from the Cultural Revolution with limited opportunities. A small, scrappy kid, he volunteered as a tour guide for foreigners at 12 to practice his English, befriending a pen pal he wrote to for years.\n\nHe failed his university entrance exam twice before getting into Hangzhou Teachers University — a school considered second-rate. He graduated in 1988 and applied for 30+ jobs, getting rejected by all of them. KFC rejected him. Harvard rejected him 10 times.\n\n## The Turning Point\n\nIn 1995, visiting Seattle for the first time, Ma typed "beer" into a web search. No Chinese beer appeared. He searched "China" — nothing. He saw a white space the size of a civilization.\n\nHe returned to China and started China Pages — China''s first internet company. It failed. He worked as a government trade official for a few years, then in 1999 gathered 17 friends in his apartment and delivered a two-hour speech about his new vision.\n\n## Building Alibaba\n\nAlibaba launched in 1999 as a B2B marketplace connecting Chinese manufacturers to global buyers. The critical decisions:\n- **Taobao** (2003): A consumer marketplace that crushed eBay China by offering free listings\n- **Alipay** (2004): Built trust by holding payment in escrow — solved China''s trust problem\n- **Alibaba Cloud**: Now the largest cloud provider in Asia\n- **2014 IPO**: $25 billion — the largest IPO in history at the time\n\n## Key Principles\n\n**Customers first, employees second, shareholders third**: Counterintuitive — but it''s what made Alibaba a platform people trusted.\n\n**Embrace failure as curriculum**: Ma counts his failures not as setbacks but as the tuition he paid for his education.\n\n**Never compete on price alone**: He positioned Alibaba to create value, not just to undercut competitors.\n\n**Think 30 years ahead**: "Today is tough, tomorrow is tougher, but the day after tomorrow is beautiful."\n\n## Legacy\n\nJack Ma retired as Alibaba''s chairman in 2019 on his 55th birthday, saying he wanted to focus on education and philanthropy. Alibaba today serves 900 million active consumers. His story resonates across Asia and beyond as proof that a kid with no connections, no family wealth, and no elite education can reshape the world.\n\n**Greatest lesson**: "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine."',
    'Bitdoin Team',
    ARRAY['jack-ma', 'alibaba', 'china', 'entrepreneurship', 'perseverance', 'e-commerce'],
    true, false, 0
  );

  -- 8. Oprah Winfrey
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Oprah Winfrey: From Poverty to an Empire Built on Empathy',
    'ໂອພຣາ ວິນເຟຣ: ຈາກຄວາມທຸກຍາກສູ່ອາລາຈັກແຫ່ງຄວາມເຫັນໃຈ',
    'Born into poverty in rural Mississippi, sexually abused as a child, Oprah Winfrey overcame every obstacle to become the most powerful woman in entertainment and the first Black female billionaire.',
    E'## Early Life\n\nOprah Gail Winfrey was born January 29, 1954, in rural Kosciusko, Mississippi, to an unmarried teenage mother. She was so poor her grandmother dressed her in potato sacks. She was sexually abused from age 9 to 13 by relatives. At 14, she gave birth to a premature baby who died.\n\nAnd yet, Oprah read. Constantly. A teacher noticed her gift for words and helped her win a scholarship to Tennessee State University.\n\n## Breaking Through\n\nAt 19, Oprah became the first Black female news anchor at Nashville''s WLAC-TV. She was hired to co-host a Chicago morning show, AM Chicago, in 1984. Within a month, she turned a third-place show into the city''s top-rated talk show.\n\nThe Oprah Winfrey Show went national in 1986. It ran for 25 seasons and was the highest-rated daytime talk show in American history. She made authors into bestsellers with a wave of her hand. She gave away cars. She interviewed presidents. She changed how America talked about abuse, addiction, and aspiration.\n\n## Building an Empire\n\n- **Harpo Productions** (1986): Oprah produced her own show — a radical act for a Black woman in the 1980s\n- **The Oprah Winfrey Show** (1986–2011): 25 seasons, 25 million viewers per episode\n- **O, The Oprah Magazine**: The most successful magazine launch in history\n- **OWN (Oprah Winfrey Network)**: A cable TV network\n- **Investments**: Stake in Weight Watchers turned $43M → $400M\n\n## Key Principles\n\n**Authenticity is a strategy**: Oprah didn''t hide her struggles. She shared them — and her audience trusted her completely because of it.\n\n**Gratitude changes everything**: Oprah kept a gratitude journal for years and credits it with her success.\n\n**Books are the greatest tool for transformation**: The Oprah Book Club made reading social — and sold millions of copies.\n\n**Use your platform for good**: Every episode had a mission beyond entertainment.\n\n## Legacy\n\nOprah Winfrey is the first Black female billionaire, worth over $2.5 billion. She has donated over $400 million to educational causes. Time magazine named her one of the 100 most influential people of the 20th century — twice.\n\n**Greatest lesson**: "Turn your wounds into wisdom."',
    'Bitdoin Team',
    ARRAY['oprah-winfrey', 'media', 'empowerment', 'resilience', 'leadership'],
    true, false, 0
  );

  -- 9. Richard Branson
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Richard Branson: The Rebel Who Built 400 Companies',
    'ຣິຊາດ ບຣານສັນ: ນັກກົບຖ່ວນທີ່ສ້າງ 400 ບໍລິສັດ',
    'Richard Branson dropped out of school at 16 with dyslexia and a failing grade. His headmaster predicted he''d either end up in prison or become a millionaire. He chose the latter — 400 times over.',
    E'## Early Life\n\nRichard Charles Nicholas Branson was born July 18, 1950, in Blackheath, London. Severe dyslexia made traditional schooling nearly impossible. His grades were terrible. At 15, he started his first business — a magazine for students.\n\nWhen he left Stowe School at 16, his headmaster told him: "Richard, you will either go to prison or become a millionaire." Both comments turned out to be half right.\n\n## The Virgin Empire Begins\n\nAt 20, Branson started a mail-order record business called **Virgin** — named because he was a virgin at business. He opened a record shop on Oxford Street in 1971, then signed the Sex Pistols and Rolling Stones to Virgin Records.\n\nIn 1984, he had an idea: start an airline. His board thought he was insane. He borrowed a plane, named it "Virgin Atlantic," and flew the first route London-Newark. He lost money for years — but built one of Britain''s most beloved brands.\n\n## Building the Virgin Group\n\nVirgin today spans 35 countries and over 400 companies:\n- **Virgin Atlantic** — pioneered Premium Economy class\n- **Virgin Mobile** — disrupted mobile telecoms\n- **Virgin Galactic** — commercial spaceflight\n- **Virgin Hotels, Trains, Health, Money** — branching into every sector\n\nThe pattern: take an established industry, find where it''s arrogant or overpriced, and disrupt it with better service and a human touch.\n\n## Key Principles\n\n**People first**: "If you look after your staff, they''ll look after your customers. It''s that simple."\n\n**Screw it, just do it**: Branson''s autobiography title captures his philosophy — overthinking is the enemy of action.\n\n**Turn adversity into advantage**: Every time Virgin faced a crisis (airline near-collapse, lawsuits), Branson used the publicity to his benefit.\n\n**Have fun or don''t bother**: If the business isn''t fun, why are you doing it?\n\n## Legacy\n\nBranson has crossed the Atlantic in a hot air balloon and catamaran, climbed Kilimanjaro, kite-surfed across the Channel, and launched himself to the edge of space in 2021. He has signed the Giving Pledge, committing the majority of his wealth to charity.\n\n**Greatest lesson**: "Business opportunities are like buses — there''s always another one coming."',
    'Bitdoin Team',
    ARRAY['richard-branson', 'virgin', 'entrepreneurship', 'adventure', 'disruption'],
    true, false, 0
  );

  -- 10. Larry Page
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Larry Page: The Student Who Decided to Organize All Knowledge',
    'ລາຣີ ເພດ: ນັກສຶກສາທີ່ຕັດສິນໃຈຈັດລະບຽບຄວາມຮູ້ທັງໝົດ',
    'Larry Page had a dream so audacious it seemed absurd: download the entire internet and rank it. That dream became Google — the most used tool in human history.',
    E'## Early Life\n\nLawrence Edward Page was born March 26, 1973, in East Lansing, Michigan. His parents were both computer science professors at Michigan State University. Larry grew up with computers literally everywhere. At 6, he was reading Popular Science and Omni magazines. By 12, he had read every book in the house.\n\n## The Stanford Dream\n\nAt Stanford''s computer science PhD program in 1995, Page met Sergey Brin. They were assigned to show each other around campus and famously argued about almost everything. That adversarial energy became the engine of innovation.\n\nPage had a singular obsession: what if you could measure the importance of a web page by how many other pages linked to it — like academic citations? He called it "BackRub," then PageRank.\n\n## Building Google\n\nPage and Brin launched Google from a Stanford dorm in 1998. Their dorm became a server farm; the university''s network nearly crashed under the load. They moved to Susan Wojcicki''s garage in Menlo Park with a $100,000 check from Andy Bechtolsheim.\n\nKey milestones:\n- **AdWords** (2000): The business model that funded everything else\n- **Gmail** (2004): Offered 1GB of storage when Yahoo offered 4MB\n- **Google Maps, YouTube, Chrome, Android**: Products that became infrastructure\n- **Alphabet** (2015): Restructured as a holding company for moonshots\n\n## Key Principles\n\n**10x thinking**: Page famously said "10% improvement requires more or less the same resources as 10x improvement. But 10x forces you to think differently."\n\n**Organize the world''s information**: The mission wasn''t to build a search engine. It was to make humanity smarter.\n\n**Shoot for the moon, land among the stars**: Waymo (self-driving cars), Verily (life sciences), Loon (internet balloons) — bets on transformative change.\n\n**Toothbrush test**: Would someone use this product twice a day, like a toothbrush? Only build things that pass the test.\n\n## Legacy\n\nGoogle processes over 8.5 billion searches a day. Android runs on over 3 billion devices. Google Maps navigates over 1 billion miles daily. Page stepped back from Alphabet''s day-to-day in 2019 but remains one of the most consequential builders of the digital age.\n\n**Greatest lesson**: "Always work hard on something uncomfortably exciting."',
    'Bitdoin Team',
    ARRAY['larry-page', 'google', 'alphabet', 'technology', 'silicon-valley', 'moonshots'],
    true, false, 0
  );

  -- 11. Sam Walton
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Sam Walton: The Farmer''s Son Who Built the World''s Largest Company',
    'ແຊມ ວໍລທັນ: ລູກຊາຍຊາວນາທີ່ສ້າງບໍລິສັດໃຫຍ່ທີ່ສຸດໃນໂລກ',
    'Sam Walton started with a single store in rural Arkansas and an obsession with low prices. By the time he died, he''d built Walmart — a company that reshaped retail, supply chains, and American life.',
    E'## Early Life\n\nSamuel Moore Walton was born March 29, 1918, in Kingfisher, Oklahoma. His family struggled through the Great Depression, and Sam learned early that every penny counted. He delivered newspapers, milked cows, and sold magazine subscriptions to help the family.\n\nHe studied economics at the University of Missouri, working his way through school. After graduation and a stint in the army, he opened a Ben Franklin franchise store in Newport, Arkansas, with a $5,000 loan.\n\n## The Walmart Revolution\n\nWalton loved to study competitors. He''d personally visit rival stores, counting inventory and talking to employees. When he opened the first Walmart in Rogers, Arkansas, in 1962, he already knew the formula:\n- Small towns (where big chains wouldn''t go)\n- Unbeatable low prices\n- Huge selection\n- Friendly service\n\nWalmart''s logistics became its competitive moat. Walton pioneered satellite communication systems that tracked inventory in real time — a decade before competitors understood the idea.\n\n## Building the Empire\n\n- **1972**: Walmart goes public at $16.50 per share. Those shares, split-adjusted, would be worth over $50,000 today\n- **1983**: Sam''s Club launches — wholesale for members\n- **1988**: First Walmart Supercenter (groceries + general merchandise)\n- **1992**: Walton dies worth $65 billion; leaves behind 1,900 stores\n- **Today**: 10,500 stores, 2.3 million employees, $600 billion in annual revenue\n\n## Key Principles\n\n**Communicate everything**: Walton held weekly Saturday morning meetings, flying in managers from across the country. Information sharing was a competitive weapon.\n\n**Celebrate your associates**: "There''s only one boss — the customer. And the customer can fire everybody in the company, from the chairman on down, simply by spending their money somewhere else."\n\n**Swim upstream**: "Swim against the current." Conventional wisdom said rural America couldn''t support big stores. Walton proved them wrong.\n\n**Control your costs**: Every dollar saved in operations was a dollar passed to customers as lower prices. The obsession with cost drove everything.\n\n## Legacy\n\nSam Walton never stopped working, never stopped learning, and never let success make him arrogant. His biography, "Made in America," is one of the most practical business books ever written.\n\n**Greatest lesson**: "High expectations are the key to everything."',
    'Bitdoin Team',
    ARRAY['sam-walton', 'walmart', 'retail', 'entrepreneurship', 'frugality'],
    true, false, 0
  );

  -- 12. Howard Schultz
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Howard Schultz: How a Kid from the Projects Sold Coffee to the World',
    'ໂຮວາດ ຊາວທ: ເດັກໜຸ່ມຈາກໂຮງຢູ່ທີ່ຂາຍກາເຟໃຫ້ໂລກ',
    'Howard Schultz grew up in a Brooklyn housing project with no safety net. He built Starbucks into a global ritual — and proved that a company''s culture, when treated as a product, becomes its greatest competitive advantage.',
    E'## Early Life\n\nHoward Schultz was born July 19, 1953, in Brooklyn, New York, in a housing project called Canarsie. His father — who never earned more than $20,000 a year — broke his ankle at work and lost his job, health insurance, and income in one accident. That sight of his father beaten down by a system with no safety net shaped everything Schultz would later build.\n\nSchultz was the first in his family to attend college, earning a football scholarship to Northern Michigan University.\n\n## The Italian Revelation\n\nIn 1983, Schultz was head of marketing for a small Seattle coffee company called Starbucks (it had four stores). He traveled to Milan for a trade show and visited an espresso bar. He was transfixed: Italians didn''t just buy coffee — they had a ritual. A third place between home and work.\n\nHe came back and told Starbucks'' founders: we need to serve espresso drinks. They said no. So Schultz left and opened his own coffee bar, Il Giornale. Two years later, he bought Starbucks for $3.8 million.\n\n## Building the Third Place\n\nSchultz''s genius wasn''t coffee — it was atmosphere. He created:\n- Comfortable chairs, free Wi-Fi, no pressure to leave\n- Consistent, customizable drinks with friendly baristas who knew your name\n- A reward program that turned customers into habits\n- **Health insurance for part-time workers**: In 1988, radical. Today, the defining reason Starbucks attracts loyal partners\n\nStarbucks grew from 11 stores in 1987 to over 32,000 locations in 80+ countries.\n\n## Key Principles\n\n**Build a company your father never had**: Schultz designed benefits — health care, stock options, tuition coverage — that he wished existed for his father.\n\n**Don''t sacrifice long-term integrity for short-term performance**: When Starbucks suffered during the 2008 recession, Schultz returned as CEO, closed 7,000 stores for one afternoon to retrain every barista.\n\n**Employees are your first customers**: If your people love working there, customers feel it.\n\n## Legacy\n\nStarbucks revolutionized how the world thinks about coffee, retail experience, and employee benefits. Schultz has written "Onward" and "Pour Your Heart Into It" — two of the most human business books ever published.\n\n**Greatest lesson**: "In life, you can blame a lot of people and you can wallow in self-pity, or you can pick yourself up and say, ''Listen, I have to be responsible for myself.''"',
    'Bitdoin Team',
    ARRAY['howard-schultz', 'starbucks', 'coffee', 'brand-building', 'leadership'],
    true, false, 0
  );

  -- 13. Ray Dalio
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Ray Dalio: Principles Over Everything',
    'ເຣ ດາລີໂອ: ຫຼັກການເໜືອທຸກສິ່ງ',
    'Ray Dalio turned a $300 investment into Bridgewater Associates — the world''s largest hedge fund. His obsession with radical transparency and documenting life''s patterns produced one of the most unusual management philosophies in history.',
    E'## Early Life\n\nRaymond Thomas Dalio was born August 8, 1949, in Jackson Heights, Queens, New York. His father was a jazz musician. At 12, he caddied at a golf course and used his tip money to buy Northeast Airlines stock for $300. The airline was subsequently acquired and his shares tripled — and he was hooked.\n\nHe studied finance at Long Island University and earned an MBA from Harvard Business School, then joined Shearson Hayden Stone as a commodities clerk.\n\n## Building Bridgewater\n\nIn 1975, Dalio founded Bridgewater Associates from his New York apartment. He advised companies on currency and interest-rate risk before pivoting to a pure investment fund. What made Bridgewater different was not just returns but *process*:\n\n- He believed markets were driven by cause-and-effect relationships that could be turned into rules (algorithms)\n- He recorded and systematized every decision and its outcome\n- He built a culture where any employee could challenge any idea, including the founder''s\n\n**The 1982 Mistake**: Dalio publicly predicted a depression following Mexico''s debt default. He was spectacularly wrong. Bridgewater nearly went under. This humiliation became a turning point: he became obsessed with finding out where his thinking was wrong, not where he was right.\n\nBy the 2000s, Bridgewater managed $160 billion — becoming the world''s largest hedge fund.\n\n## Key Principles\n\n**Radical transparency**: All meetings are recorded and open to all employees. All feedback must be honest, even to the CEO. Bluntness, not politics.\n\n**Embrace pain and reflection**: "Pain + Reflection = Progress." Mistakes are only bad if you don''t learn from them.\n\n**Believability-weighted decision making**: Not everyone''s opinion is equal. Weight opinions based on demonstrated track record.\n\n**Meritocracy of ideas**: The best idea wins — regardless of who said it.\n\n**Know your two biggest weaknesses**: Most people fail not from lack of ability but from inability to see their own blind spots.\n\n## Legacy\n\nDalio published **Principles** (2017) — a book that detailed his life and management philosophy. It became an international bestseller and has been used by companies, governments, and individuals worldwide. He has pledged to give away the majority of his wealth.\n\n**Greatest lesson**: "Pain is the signal that something needs to change. Don''t hide from it — study it."',
    'Bitdoin Team',
    ARRAY['ray-dalio', 'bridgewater', 'investing', 'principles', 'leadership', 'hedge-fund'],
    true, false, 0
  );

  -- 14. Reed Hastings
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Reed Hastings: The $40 Late Fee That Disrupted Hollywood',
    'ຣີດ ເຮສຕິ້ງ: ຄ່າປັບ $40 ທີ່ທຳລາຍ Hollywood',
    'Reed Hastings was fined $40 for returning Apollo 13 late. That frustration sparked Netflix — a company that killed Blockbuster, disrupted Hollywood, and redefined how the world consumes entertainment.',
    E'## Early Life\n\nWilmot Reed Hastings Jr. was born October 8, 1960, in Boston, Massachusetts. After graduating from Bowdoin College with a mathematics degree, he joined the Peace Corps and taught math in Swaziland (now Eswatini) for two years — an experience that gave him a global perspective and deep appreciation for education.\n\nHe earned a master''s in computer science from Stanford, then started his first company, Pure Atria (software testing tools), which he sold for $700 million in 1997.\n\n## The $40 That Changed Entertainment\n\nIn 1997, Hastings returned Apollo 13 to Blockbuster six weeks late and was charged $40. Embarrassed, he went to the gym and thought: what if video rentals worked like a gym membership — a flat monthly fee, no late fees?\n\nHe co-founded Netflix in 1997 as a DVD-by-mail service. The model was elegant: subscribers chose movies online, DVDs arrived by mail, and returns were postage-paid with no due date.\n\n## The Pivot That Saved Netflix\n\nIn 2007, Hastings saw the future and made the decision that defines Netflix: **streaming**. He began offering internet video alongside DVDs, investing hundreds of millions in content deals while traditional studios hesitated.\n\nIn 2011, Hastings split Netflix''s DVD and streaming services in the "Qwikster" debacle — subscribers revolted, the stock dropped 77%. He reversed course and learned a vital lesson about change management.\n\nThen came the masterstroke: **Original Content**.\n- **House of Cards** (2013): First original series; streamed entire season at once — inventing "binge-watching"\n- **Orange Is the New Black**, **Stranger Things**, **The Crown**: Emmy-winning, culture-defining content\n- Netflix spent $17 billion on content in 2023 alone\n\n## Key Principles\n\n**No rules rules**: Hastings abolished formal vacation policies, expense accounts, and approval processes — replacing rules with judgment and context.\n\n**Hire only extraordinary people**: Netflix''s famous "Keeper Test": Would you fight hard to keep this person? If not, they shouldn''t be here.\n\n**Radical candor over politeness**: Netflix culture prizes honest, direct feedback over comfortable mediocrity.\n\n**Adapt before you must**: Hastings cannibalized the DVD business before anyone else could — accepting short-term pain for long-term survival.\n\n## Legacy\n\nNetflix has over 260 million subscribers in 190 countries. It has changed what we watch, how we watch, and when we watch it. Hastings stepped back as CEO in 2023 and has committed $100 million to historically Black colleges.\n\n**Greatest lesson**: "Most companies make incremental improvements. Sustain your culture of innovation or someone will disrupt you the same way you disrupted everyone else."',
    'Bitdoin Team',
    ARRAY['reed-hastings', 'netflix', 'streaming', 'disruption', 'technology', 'entertainment'],
    true, false, 0
  );

  -- 15. Indra Nooyi
  INSERT INTO knowledge_posts (category_id, type, title_en, title_lo, excerpt_en, content_en, author, tags, is_published, is_featured, views)
  VALUES (
    bio_cat_id, 'biography',
    'Indra Nooyi: The CEO Who Led PepsiCo from the Front',
    'ອິນດຣາ ນູຍີ: CEO ທີ່ນຳທັບ PepsiCo ຈາກດ້ານໜ້າ',
    'Indra Nooyi arrived in America with $50 and a suitcase. She rose to become CEO of PepsiCo for 12 years, guiding one of the world''s largest food companies through a bold transformation with grace and vision.',
    E'## Early Life\n\nIndra Krishnamurthy Nooyi was born October 28, 1955, in Chennai (then Madras), India, into a middle-class family. Her grandfather challenged her to read a newspaper every day and debate ideas at dinner. Her mother set an unusual rule: every evening, Indra and her sister had to give a speech as if they were prime minister of India.\n\nShe earned a bachelor''s in physics, chemistry, and mathematics from Madras Christian College, then an MBA from the Indian Institute of Management Calcutta. She arrived at Yale School of Management for a master''s degree with $50 in her pocket and no winter coat.\n\n## The Rise\n\nAfter Yale, Nooyi worked at Boston Consulting Group, Motorola, and ABB before joining PepsiCo in 1994. She engineered some of the most important strategic moves in the company''s history:\n\n- Sold Pizza Hut, Taco Bell, and KFC (1997) — freeing PepsiCo to focus on beverages and snacks\n- Led the acquisition of Tropicana (1998) for $3.3 billion\n- Orchestrated the $13.4 billion Quaker Oats acquisition (2001) — bringing Gatorade into the portfolio\n\nIn 2006, she was named CEO. She was only the 11th woman and first Indian-American to lead a Fortune 50 company.\n\n## Performance With Purpose\n\nNooyi''s transformative strategy: "Performance with Purpose." The idea that a company can be financially successful *and* beneficial to society.\n\n- Shifted portfolio toward healthier products (reducing sodium, sugar, fats)\n- Invested in sustainable packaging and water conservation\n- Created a culture of inclusion and diversity\n- Revenue grew from $35 billion (2006) to $63 billion (2017) under her leadership\n\n## Key Principles\n\n**Write letters to your employees'' parents**: Nooyi famously wrote letters to the parents of her top executives, thanking them for raising such capable children. The effect on loyalty and culture was profound.\n\n**Lead with empathy**: "Whatever anybody says or does, assume positive intent."\n\n**Strategy is about choices**: You cannot be everything to everyone. Choose where to compete and commit fully.\n\n**Balance humility with ambition**: Nooyi has said she never stopped feeling like an outsider — and that vulnerability made her more curious, more empathetic, and more effective.\n\n## Legacy\n\nIndra Nooyi is now a member of Amazon''s board and a visiting fellow at MIT. She published her memoir, "My Life in Full," in 2021 — a candid account of navigating power, identity, and family at the top.\n\n**Greatest lesson**: "Just because you are CEO, don''t think you have landed. You must continually increase your learning, the way you think, and the way you approach the organization."',
    'Bitdoin Team',
    ARRAY['indra-nooyi', 'pepsico', 'leadership', 'diversity', 'strategy', 'women-in-business'],
    true, false, 0
  );

END $$;
